//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anz.LMJ.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discussion()
        {
            this.DiscussionParticipants = new HashSet<DiscussionParticipant>();
            this.Discussions1 = new HashSet<Discussion>();
            this.DiscussionsFiles = new HashSet<DiscussionsFile>();
        }
    
        public long Id { get; set; }
        public long SubmissionId { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public bool isProofReading { get; set; }
        public bool isPrereview { get; set; }
        public bool isReview { get; set; }
        public bool isCopyEditing { get; set; }
        public Nullable<long> ChannelId { get; set; }
        public long SenderId { get; set; }
        public bool isClosed { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscussionParticipant> DiscussionParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discussion> Discussions1 { get; set; }
        public virtual Discussion Discussion1 { get; set; }
        public virtual Submission Submission { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscussionsFile> DiscussionsFiles { get; set; }
    }
}
