//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anz.LMJ.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscussionsFile
    {
        public long Id { get; set; }
        public Nullable<long> DiscussionId { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<long> ComponentId { get; set; }
    
        public virtual Discussion Discussion { get; set; }
    }
}
