//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anz.LMJ.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journal()
        {
            this.Libraries = new HashSet<Library>();
            this.Payments = new HashSet<Payment>();
            this.Sections = new HashSet<Section>();
        }
    
        public long Id { get; set; }
        public Nullable<bool> isSelfRegister { get; set; }
        public Nullable<bool> isMultiLingual { get; set; }
        public Nullable<int> PreferredLangaugeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public string Initials { get; set; }
        public string Abbreviation { get; set; }
        public string Publisher { get; set; }
        public string OnlineISSN { get; set; }
        public string PrintISSN { get; set; }
        public string Logo { get; set; }
        public string MailingAddress { get; set; }
        public string PrincipalName { get; set; }
        public string PrincipalTitle { get; set; }
        public string PrincipalEmail { get; set; }
        public string principalPhone { get; set; }
        public string TechnicalSupportContact { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
    
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Library> Libraries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
    }
}
