//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anz.LMJ.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookUp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LookUp()
        {
            this.LookUp1 = new HashSet<LookUp>();
            this.LookUpMultiLanguages = new HashSet<LookUpMultiLanguage>();
        }
    
        public long Id { get; set; }
        public Nullable<int> TableId { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> isPublished { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> ParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LookUp> LookUp1 { get; set; }
        public virtual LookUp LookUp2 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LookUpMultiLanguage> LookUpMultiLanguages { get; set; }
    }
}
