//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anz.LMJ.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public long UserId { get; set; }
        public string CoverImage { get; set; }
        public string ISSN { get; set; }
        public string EISSN { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string Volume { get; set; }
    
        public virtual User User { get; set; }
    }
}
