//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anz.LMJ.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public long Id { get; set; }
        public string Text { get; set; }
        public Nullable<int> NbOfStars { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public string FName { get; set; }
        public bool IsDeleted { get; set; }
        public long SubmissionId { get; set; }
        public Nullable<bool> IsAdmit { get; set; }
        public string LName { get; set; }
    }
}
