//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anz.LMJ.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionInProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubmissionInProcess()
        {
            this.UserResponsibleInProcesses = new HashSet<UserResponsibleInProcess>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ProcessId { get; set; }
        public Nullable<long> SubmissionId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
    
        public virtual Process Process { get; set; }
        public virtual Submission Submission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserResponsibleInProcess> UserResponsibleInProcesses { get; set; }
    }
}
