//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anz.LMJ.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionFile
    {
        public long Id { get; set; }
        public Nullable<long> SubmissionId { get; set; }
        public Nullable<long> ComponentId { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> isAcceptedforReview { get; set; }
        public Nullable<bool> isAcceptedforCopyEditing { get; set; }
        public Nullable<bool> isAcceptedforProduction { get; set; }
        public Nullable<bool> isRevision { get; set; }
        public Nullable<bool> isCopyedited { get; set; }
        public Nullable<bool> isSubmission { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Caption { get; set; }
        public Nullable<long> Order { get; set; }
    
        public virtual Submission Submission { get; set; }
        public virtual User User { get; set; }
    }
}
