//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anz.LMJ.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionStatu
    {
        public long Id { get; set; }
        public Nullable<long> SuibmissionId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<bool> isSkip { get; set; }
        public Nullable<bool> isArchived { get; set; }
        public Nullable<bool> isReed { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
    
        public virtual Submission Submission { get; set; }
        public virtual User User { get; set; }
    }
}
