//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anz.LMJ.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Submission()
        {
            this.Contributors = new HashSet<Contributor>();
            this.Discussions = new HashSet<Discussion>();
            this.EmailLogs = new HashSet<EmailLog>();
            this.Galleys = new HashSet<Galley>();
            this.SubmissionFiles = new HashSet<SubmissionFile>();
            this.SubmissionInProcesses = new HashSet<SubmissionInProcess>();
            this.SubmissionStatus = new HashSet<SubmissionStatu>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public string GUID { get; set; }
        public long SectionId { get; set; }
        public Nullable<long> StudyTypeId { get; set; }
        public string CommentsForEditor { get; set; }
        public string Prefix { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Abstract { get; set; }
        public Nullable<long> LibraryId { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
        public string MiniDescription { get; set; }
        public string CoverPhoto { get; set; }
        public Nullable<long> ResearchId { get; set; }
        public Nullable<long> QuestionId { get; set; }
        public Nullable<long> SubjectId { get; set; }
        public Nullable<long> ArticleTypeId { get; set; }
        public bool isDraft { get; set; }
        public bool isApproved { get; set; }
        public string SourcesOfFunding { get; set; }
        public string ConflictsOfInterests { get; set; }
        public string Significance { get; set; }
        public Nullable<long> SpecialitiesId { get; set; }
        public Nullable<long> IssueId { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<bool> IsEditorsPick { get; set; }
        public Nullable<bool> IsTopReader { get; set; }
        public string BannerImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contributor> Contributors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discussion> Discussions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailLog> EmailLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Galley> Galleys { get; set; }
        public virtual Library Library { get; set; }
        public virtual Section Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionFile> SubmissionFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionInProcess> SubmissionInProcesses { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionStatu> SubmissionStatus { get; set; }
    }
}
